SUMMARY = "For ZUBoard with OpenAMP support"
DESCRIPTION = "An image including OpenAMP, libmetal, and device tree support for ZUBoard."

# Please copy the following lines to your machine configuration file which is generated by the gen-machine-conf
# DISTRO_FEATURES:append = " openamp"
# IMAGE_INSTALL:append = " open-amp libmetal open-amp-device-tree"


